---
development:
  cloud_name: roguephoto
  api_key: '619556283193874'
  api_secret: xFUqpOJ2SPPaKKf84fQfVx6OEnY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: roguephoto
  api_key: '619556283193874'
  api_secret: xFUqpOJ2SPPaKKf84fQfVx6OEnY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: roguephoto
  api_key: '619556283193874'
  api_secret: xFUqpOJ2SPPaKKf84fQfVx6OEnY
  enhance_image_tag: true
  static_image_support: false

ddd